//Problem 2: Even Fibonacci numbers
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var evenFibonacciNum = function(n) {
	if (n < 3)
	{
		return 0;
	}

	var sum = 2;

	var i = 2; //Fn-1
	var j = 3; //Fn
	while (j < n)
	{
		if ( j % 2 === 0)
		{
			sum += j;
		}

		j += i; 	// j = Fn+1
		i = j - i; // i = Fn
	}
	return sum;
}